name: My Plugin Deploy Action
on:
  push:
    branches:
      - master

jobs:
  tag:
    name: uploader
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: WordPress Plugin Deploy
        run: |
          svn checkout --username "jamesnotbond" --password "12345678aA" https://james-not-bond.unfuddle.com/svn/james-not-bond_four/
          rsync -a $GITHUB_WORKSPACE/trunk/ james-not-bond_four/trunk
          rsync -a $GITHUB_WORKSPACE/assets/ james-not-bond_four/trunk
          cd james-not-bond_four
          svn add . --force
          svn commit -m "Updated!!!!!!!" --no-auth-cache --non-interactive  --username "jamesnotbond" --password "12345678aA"