name: My Plugin Deploy Action
on:
  push:
    branches:
      - master
jobs:
  tag:
    name: LOLO Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress Plugin Deploy (hehe)
        uses: ahmadhaseeb4/plugin-deployer@stable
        env:
          SVN_PASSWORD: "=> PASSWORD"
          SVN_USERNAME: "=> USERNAME"
          SVN_URL: "=> SVN URL"


