name: My Plugin Deploy Action
on:
  push:
    branches:
      - master

jobs:
  tag:
    name: uploader
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: WordPress Plugin Deploy
        run: |
          svn checkout --username "jamesnotbond" --password "12345678aA" https://james-not-bond.unfuddle.com/svn/james-not-bond_one/
          echo "Checking out is done..."
          echo "Your GITHUB_WORKSPACE contains:"
          ls $GITHUB_WORKSPACE
          echo "End of GITHUB_WORKSPACE directory"
          ls james-not-bond_one
        env:
          URL: "https://james-not-bond.unfuddle.com/svn/james-not-bond_one/"
          SVN_USERNAME: "jamesnotbond"
          SVN_PASSWORD: "12345678aA"