name: My Plugin Deploy Action
on:
  push:
    branches:
      - master

jobs:
  tag:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: WordPress Plugin Deploy
        uses: ahmadhaseeb4/plugin-deployer@stable
        env:
          URL: "https://james-bond.unfuddle.com/svn/james-bond_ah/"
          SVN_USERNAME: "muhammad007"
          SVN_PASSWORD: "12345678aA"
          hellO: "hello"